FROM datastax/dse-server

MAINTAINER Jonathan Newell version: 0.1

USER root

# Get Https Transport for apt-get
RUN apt-get update
RUN apt-get install apt-transport-https
RUN apt-get install -y netcat
RUN apt-get install -y maven

#Prepare for re-direct
RUN touch /var/log/datastax.log
RUN chmod 777 /var/log/datastax.log

COPY startup-cassandra-entrypoint.sh /startup-cassandra-entrypoint.sh

ENTRYPOINT ["/startup-cassandra-entrypoint.sh"]

CMD ["/bin/bash"]
